// User & Auth
export type Role = 'student' | 'staff' | 'admin';

export interface User {
  id: string;
  name: string;
  phone: string;
  email?: string;
  role: Role;
  canteenId: string | null;      // set for staff only
  canteenName?: string;
  mustChangePassword?: boolean;
}

export interface AuthResponse {
  accessToken: string;
  user: User;
}

export interface ApiErrorBody {
  error: {
    code: string;
    message: string;
    details?: Record<string, unknown>;
  };
}

// Order & Payment Enums
export type OrderStatus = 'placed' | 'queued' | 'preparing' | 'ready' | 'completed' | 'cancelled';
export type PaymentStatus = 'pending' | 'paid' | 'failed' | 'refunded_to_wallet';
export type WalletEntryType =
  | 'checkout_hold'
  | 'checkout_capture'
  | 'hold_release'
  | 'refund_credit'
  | 'admin_adjustment'
  | 'expiry';

// Canteen
export interface Canteen {
  id: string;
  name: string;
  location: string;
  isOpen: boolean;
  operatingHours: { open: string; close: string }; // "08:00"
  imageUrl?: string;
  liveQueue?: { activeOrders: number; estimatedWaitMins: number }; // from ML/fallback
}

// Menu
export interface MenuItem {
  id: string;
  canteenId: string;
  name: string;
  price: number;          // rupees, 2dp
  category: string;
  isAvailable: boolean;
  imageUrl?: string;
  isVeg?: boolean;        // FE request to Member 1 (Indian campus UX need)
  basePrepSeconds?: number;
}

export interface ComboSuggestion {
  itemIds: string[];
  label: string;          // "Cold Coffee + Grilled Veg Sandwich"
  savings?: number;
  confidence: number;
}

// Order
export interface OrderLine {
  menuItemId: string;
  name: string;
  quantity: number;
  priceAtOrderTime: number;
}

export interface Order {
  id: string;
  orderUid: string;       // PKT-20261005-0042
  tokenNo: string;        // A-14
  canteenId: string;
  canteenName: string;
  studentName?: string;   // staff view only
  status: OrderStatus;
  paymentStatus: PaymentStatus;
  items: OrderLine[];
  totalAmount: number;
  walletAmountApplied: number;
  gatewayAmount: number;
  estimatedPrepSeconds: number | null;
  targetPickupTime: string | null; // ISO
  createdAt: string;
  updatedAt: string;
  cancelReason?: string;
  verifyAttemptsLeft?: number;     // staff view
  isLocked?: boolean;              // 5 failed attempts
}

// Checkout
export interface CreateOrderRequest {
  canteenId: string;
  items: { menuItemId: string; quantity: number }[];
  useWallet: boolean;
  idempotencyKey: string;          // uuid generated by FE per checkout attempt
}

export interface CreateOrderResponse {
  order: Order;
  pickupCode: string;              // RAW 4-digit, returned ONCE
  razorpay?: { orderId: string; amount: number; currency: 'INR'; keyId: string }; // absent if fully wallet-paid
}

// Wallet
export interface Wallet {
  balance: number;
  updatedAt: string;
}

export interface LedgerEntry {
  id: number;
  entryType: WalletEntryType;
  amount: number;
  orderUid?: string;
  reason: string;
  balanceAfter: number;
  createdAt: string;
}

// Real-Time Socket Events
export interface ServerToClientEvents {
  'order:new': (order: Order) => void;
  'order:status_changed': (p: { orderId: string; from: OrderStatus; to: OrderStatus; order: Order }) => void;
  'order:eta_updated': (p: { orderId: string; estimatedPrepSeconds: number; targetPickupTime: string }) => void;
  'order:call_to_walk': (p: { orderId: string; tokenNo: string; counter: string }) => void;
  'order:cancelled': (p: { orderId: string; reason: string; refundedAmount: number }) => void;
  'menu:availability_changed': (p: { menuItemId: string; isAvailable: boolean }) => void;
  'canteen:status_changed': (p: { canteenId: string; isOpen: boolean }) => void;
  'wallet:updated': (p: Wallet) => void;
}

export interface ClientToServerEvents {
  'room:join': (p: { room: string }) => void;
  'room:leave': (p: { room: string }) => void;
}
